line-length = 88

exclude = [
  "examples",
  "doc",
  "tests"
]

[lint]
select = [
  "D",
  "E", "W",
  "F",
  "ARG",
  "I",
]
ignore = [
  "E501",
  "D107", # missing docstring in __init__
  "F722",
  "F821"
]

[lint.pydocstyle]
convention = "google"

[lint.per-file-ignores]
"*tests/*" = ["D", "S101"]
"__init__.py" = ["F401"]